### PR TITLE
Add Traditional Chinese (Taiwan) translation

### PR DESCRIPTION
**Pull request by tatsuz0u**
This pull request aims to include the addition of Traditional Chinese (Taiwan) translation.
By implementing this translation, users who prefer Traditional Chinese as spoken in Taiwan will have the option to use the software or content in their preferred language variant.

### CODE REVIEW

**Comment by tatsuz0u** [comment]
@Kota1021 
Hey! Before merging, could you please hold off until I specifically request? I'm planning to reach out to some native speaker friends for assistance.

**Comment by Kota1021** [comment]
Cool.
Sure, i'll wait for a possible revised version for Fanti Chinese.
Thanks :)

**Comment by tatsuz0u** [comment]
@Kota1021 I believe it's ready for merge now. 🙋

**Review by Kota1021 — APPROVED** [review]

**Comment by Kota1021** [comment]
Thanks😆

**Pull request merged**
